# Generated by Django 3.2.6 on 2021-08-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='adding_date',
            field=models.DateTimeField(),
        ),
    ]
