# Generated by Django 3.2.6 on 2021-08-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_adding_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='adding_date',
        ),
    ]
